---
- name: add mongodb 4.0 signing key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.0.asc

- name: add mongodb 4.0 repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu {{ ansible_lsb.codename }}/mongodb-org/4.0 multiverse
    filename: mongodb

- name: install mongodb packages
  apt:
    name:
      - mongodb-org
      - ssl-cert  # for snakeoil certificate
      # for parsing json
      - jq
      # for ansible
      - python-pymongo
      - python-pip
      - python3-pymongo
      - python3-pip

- name: upgrade to pymongo >3.7 to avoid problems with SCRAM-SHA-256
  # see: https://github.com/ansible/ansible/issues/44970
  pip:
    name: pymongo>3.7
    executable: "{{ item }}"
  loop: [pip, pip3]
...
