---
- name: install mongodb 4.0
  import_tasks: install.yml
  tags: srv_mongodb_install

- name: configure ssl in mongodb
  import_tasks: ssl.yml
  tags: srv_mongodb_ssl

- name: create mongodb configuration file
  template:
    src: mongod.conf
    dest: /etc/mongod.conf
    owner: root
    group: mongodb
    mode: 0644
  notify: restart mongodb service
  tags: srv_mongodb_config

- name: setup mongodb service
  import_tasks: service.yml
  tags: srv_mongodb_service

- name: set mongodb administrator password
  import_tasks: password.yml
  tags: srv_mongodb_password

- name: apply mongodb changes now
  meta: flush_handlers
  tags: srv_mongodb_password
...
