---
name: Molecule test
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

env:
  ROLE_NAME: ivansible.srv_mongodb
  ANSIBLE_FORCE_COLOR: true

jobs:
  localhost_test:
    name: test on host
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          ## Issue:
          ##   Test fails on github xenial runner with permission denied,
          ##   probably due to invalid unix mode of pymongo module files.
          ##     /usr/local/lib/python3.5/dist-packages/molecule/provisioner/ansible/plugins/filter/molecule_core.py
          ##     /usr/local/lib/python3.5/dist-packages/pymongo-3.11.0.dist-info
          ##     drwx--S---  2 root staff   pymongo
          ##     drwx--S---  2 root staff   pymongo-3.11.0.dist-info
          ## Workaround:
          ##   skip github test on xenial atm.
          # - ubuntu-16.04
          - ubuntu-18.04
    env:
      SCENARIO: localhost
      IVATEST_FIREWALL: ferm
      IVATEST_SSH_SERVER: false

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ivansible/${{ env.ROLE_NAME }}

      - name: Workaround for github issue with heroku gpg key
        run: curl -sL https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        if: matrix.os == 'ubuntu-16.04'

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          sudo -H pip3 install docker jmespath netaddr boto3 mitogen molecule pytest testinfra
          # also pulled: ansible-lint yamllint flake8

      - name: Run test
        shell: bash
        run: cd ivansible/$ROLE_NAME && molecule test -s $SCENARIO

  docker_test:
    name: tests in docker
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      SCENARIO: default
      IVATEST_FIREWALL: none
      IVATEST_SSH_SERVER: true

    steps:  # copy-pasting above steps since anchors are unsupported
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ivansible/${{ env.ROLE_NAME }}

      - name: Install requisites
        shell: bash
        run: |
          # stock and pypy flavors of PyYAML are incompatible:
          sudo apt-get remove -q -y python3-yaml
          sudo -H pip3 install -U pip setuptools wheel
          sudo -H pip3 install docker jmespath netaddr boto3 mitogen molecule pytest testinfra
          # also pulled: ansible-lint yamllint flake8

      - name: Run test
        shell: bash
        run: cd ivansible/$ROLE_NAME && molecule test -s $SCENARIO
...
